name: "Create/Update tag"
description: "Creates or updates a tag for a given commit."
author: "Rick Staa"
inputs:
  github_token:
    description: "GITHUB_TOKEN. Optional if you use checkout@v2 action."
    default: "${{ github.token }}"
  tag:
    description: "Tag you want to create or update."
    required: true
  message:
    description: "Tag message."
    required: false
  commit_sha:
    description: The commit SHA hash on which you want to push the tag. Uses latest commit by default.
    required: false
  force_push_tag:
    description: "Optional. Force push the tag. Defaults to 'false'."
    required: false
    default: "false"
  include_submodules:
    description: "Optional. Creates the same tag in all submodules with their checked out commit SHA. Defaults to 'false'."
    required: false
    default: "false"
  only_submodule:
    description: "Optional. Create the tag only in the specified submodule. Defaults to empty."
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "tag"
  color: "blue"
